services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Supseven\CanonicalFiles\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\ExpressionLanguage\Resolver:
    arguments:
      $context: 'site'
      $variables: []
